In [1]:
import numpy as np

In [2]:
#indexing of 1-d array
arr = np.array([1,2,3,4])
print(arr[2])

3


In [3]:
#slicing of 1-d array
print(arr[1:3])

[2 3]


In [4]:
#declaring 2-d array
arr1 = np.array([1,2,3,4,5,6])
res = arr1.reshape(2,3)
print(res)

[[1 2 3]
 [4 5 6]]


In [5]:
#indexing of 2-d array
print(res[1,1])    #here we have to give two parameters: first is row number and second is column number 

5


In [6]:
#slicing of 2-d array
#here first we have to pass row number and then we will pass the slicing criteria
print(res[1,0:2]) 

[4 5]


In [7]:
#declaring 3-d array
arr3 = np.arange(1,13)
res2 = arr3.reshape(2,3,2)
print(res2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#indexing 3-d array
#in this we have to pass three parameters- layer:row no. of layer:column no.of layer
print(res2[0,1,1])  

4


In [9]:
#slicing 3-d array
#here we pass three parameters- layer no.:row no. of layer:slicing criteria
print(res2[1,1,0:2])

[ 9 10]
