In [2]:
import numpy as np

**Insert:-**

In [4]:
var = np.array([1,2,3,4])

print(var)

[1 2 3 4]


In [6]:
#insert() used to insert element at specific position in array
'''It takes three parameters:
    1. Name of variable in which array is stored
    2. Position at which we wanted to insert element
    3. The element which we wanted to insert '''
ins = np.insert(var, 2, 48)
print(ins)

[ 1  2 48  3  4]


In [8]:
#inserting element in 2-d array
var1 = np.array([[1,2,3],[4,5,6]])

ins1 = np.insert(var1, 2, 48, axis=0) #inserting into row axis =0
print(ins1)


[[ 1  2  3]
 [ 4  5  6]
 [48 48 48]]


In [9]:
var1 = np.array([[1,2,3],[4,5,6]])

ins1 = np.insert(var1, 2, 48, axis=1) #inserting into column axis =1
print(ins1)


[[ 1  2 48  3]
 [ 4  5 48  6]]


In [10]:
var1 = np.array([[1,2,3],[4,5,6]])

ins1 = np.insert(var1, 2, (8,9,10), axis=0) #we can insert multiple elemnts as well
print(ins1)


[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


***append:***

In [12]:
#insert value in last of sequence
var3 = np.array([1,2,3,4,5])

x = np.append(var3, 6)
print(x)

[1 2 3 4 5 6]


**Delete:-**

In [14]:
#delete() used to delete an element
#it takes two parameter: variable in which array is stored and position of element to be deleted
arr = np.array([1,2,3,4,5])

de = np.delete(arr, 2)
print(de)

[1 2 4 5]
