**Joining Array**

•Joining array means adding tow or more array to form a single array.

•The array with similar shape and size can only be added,we can't add two arrays if their size is different

•***Ex:-*** There are two arrays given whose shape is 2x2 and 2x2,they can be added but if we have 2x3 and 2x2 then they can't be added.

•We can add arays on the basis of axis also.

In [1]:
import numpy as np

In [4]:
#1-d array
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

arr = np.concatenate((var,var1))  #concatenate() is used to join two numpy arrays

print("Concatenated array is:- ",arr)

Concatenated array is:-  [1 2 3 4 5 6 7 8]


In [8]:
#2-d array
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[5,6],[7,8]])

arr1 = np.concatenate((vr,vr1), axis = 1)  #added row wise 

print(vr)

print()
print(vr1)
print()

print("Concatenated array is:- ")
print(arr1)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

Concatenated array is:- 
[[1 2 5 6]
 [3 4 7 8]]


In [9]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[5,6],[7,8]])

arr1 = np.concatenate((vr,vr1), axis = 0)  #added column wise 

print(vr)

print()
print(vr1)
print()

print("Concatenated array is:- ")
print(arr1)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

Concatenated array is:- 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**stack()**

In [13]:
#stack() is also used for joining arrays

var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

arr_1 = np.stack((var_1,var_2))  

print("Concatenated array is:- ")
print(arr_1)

Concatenated array is:- 
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

arr_1 = np.dstack((var_1,var_2))  #dstack join arrays along height

print("Concatenated array is:- ")
print(arr_1)

Concatenated array is:- 
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [17]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

arr_1 = np.hstack((var_1,var_2))  #hstack join array along rows

print("Concatenated array is:- ")
print(arr_1)

Concatenated array is:- 
[1 2 3 4 5 6 7 8]


In [20]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

arr_1 = np.vstack((var_1,var_2))  #vstack join array along column

print("Concatenated array is:- ")
print(arr_1)

Concatenated array is:- 
[[1 2 3 4]
 [5 6 7 8]]


**Split Array**

In [28]:
ar = ([1,2,3,4,5,6])

print(ar)

[1, 2, 3, 4, 5, 6]


In [30]:
#spliting array using array_split() function
#we have to pass array which we want to split and in how many parts we want to split
ar_1 = np.array_split(ar,3)  
print(ar_1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
#accessing different arrays after spliting
print(ar_1[1])

[3 4]


In [34]:
#2-d array
ar1 = ([[1,2,3],[4,5,6],[7,8,9]])
print(ar1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [35]:
#spliting 2-d array
ar_2 = np.array_split(ar1,3)  
print(ar_2)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [37]:
#we can aplit 2-d array along axis also
ar_2 = np.array_split(ar1,3,axis = 1)  
print(ar_2)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
